--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/BeeAZ-pm-pl/ASkyBlock
build-by-default: true
branches:
- master
projects:
  ASkyBlock:
    path: ""
    libs:
      - src: BeeAZ-pm-pl/BeeAZ/FormBuilderX/FormBuilderX
        version: ^1.0.0
...
